### ISSUE TITLE
neofs-api-csharp

### ISSUE THREAD

**Issue by leiw5173** [nspcc-dev/neofs-api-csharp#5]
Please update the readme file to link to the https://github.com/neo-ngd/neofs-api-csharp repo. 
This can help the user to find the documentation easily.
 
![image](https://user-images.githubusercontent.com/73590328/146298284-7fa09867-24a6-47ca-b284-ea46e9f633a7.png)

**Comment by alexvanin** [comment]
Done in https://github.com/nspcc-dev/neofs-api-csharp/commit/2f080d247d565f41b0b5f990472497e1e784a243
